version: '3.8'
services:
  ros-app:
    image: yahboomtechnology/ros-humble:4.1.0
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROBOT_TYPE=r2
    # volumes:
    #   - /tmp/.X11-unix:/tmp/.X11-unix
    #   - /home/jetson/temp:/root/yahboomcar_ros2_ws/temp
    #   - /home/jetson/rosboard:/root/rosboard
    #   - /home/jetson/maps:/root/maps
    #   - /dev/bus/usb/001/012:/dev/bus/usb/001/012
    #   - /dev/bus/usb/001/013:/dev/bus/usb/001/013
    # devices:
    #   - /dev/myserial:/dev/myserial
    #   - /dev/rplidar:/dev/rplidar
    #   - /dev/input:/dev/input
    #   - /dev/astradepth:/dev/astradepth
    #   - /dev/astrauvc:/dev/astrauvc
    #   - /dev/video0:/dev/video0
    ports:
      - "9090:9090"
      - "8888:8888"
    # network_mode: host
    command: bin/bash
